# Header
menu:
#  Home: /
#  Archives: /archives
  首页: /
  存档: /archives
  关于: /about
rss: /atom.xml

# Content
#excerpt_link: Read More
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- weibo

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: